### ISSUE TITLE
Serialization failure using RemoteFunc.Invoke

### ISSUE THREAD

**Issue by eddiesholl** [jduv/AppDomainToolkit#20]
Hi there,

I'm stuck trying to use RemoteFunc.Invoke to make use of a dynamic domain. It appears I'm hitting the exact serialization issue mentioned in the readme (the lambda not getting marked as serializable).

There's a class DTLogic.Slave.DynamicDomain+<>c__DisplayClass7 which is apparently trying to be serialized. Using ILSpy on my assembly, this appears to be the RemoteFunc.Invoke expression :(

    .class public auto ansi beforefieldinit DTLogic.Slave.DynamicDomain
	extends [mscorlib]System.Object
    {
	// Nested Types
	.class nested private auto ansi sealed beforefieldinit '<>c__DisplayClass7'
		extends [mscorlib]System.Object
	{

My lambda takes a custom serializable type (InvokeRequest) and returns another serializable one (InvokeResult). I've been chipping away at these to get them happy, now everything seems to be unblocked, but then this. Doh.

Finding this library has been great and saved me a bunch of time, I'm just now at the last hurdle of actually getting it running. I'd love to hear any ideas you might have on solving this. I can post a snippet if that helps.

Here's my stack trace:

System.Runtime.Serialization.SerializationException: Type 'DTLogic.Slave.DynamicDomain+<>c__DisplayClass7' in Assemb
y 'DT.Logic, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' is not marked as serializable.

Server stack trace:
   at System.Runtime.Serialization.FormatterServices.InternalGetSerializableMembers(RuntimeType type)
   at System.Runtime.Serialization.FormatterServices.GetSerializableMembers(Type type, StreamingContext context)
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitMemberInfo()
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object obj, ISurrogateSelector su
rogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, Object
riter objectWriter, SerializationBinder binder)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(WriteObjectInfo objectInfo, NameInfo memberN
meInfo, NameInfo typeNameInfo)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, Header[] inHeaders, __Bina
yWriter serWriter, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object gr
ph, Header[] headers, Boolean fCheck)
   at System.Runtime.Remoting.Channels.CrossAppDomainSerializer.SerializeMessageParts(ArrayList argsToSerialize)
   at System.Runtime.Remoting.Messaging.SmuggledMethodCallMessage..ctor(IMethodCallMessage mcm)
   at System.Runtime.Remoting.Messaging.SmuggledMethodCallMessage.SmuggleIfPossible(IMessage msg)
   at System.Runtime.Remoting.Channels.CrossAppDomainSink.SyncProcessMessage(IMessage reqMsg)

Exception rethrown at [0]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at AppDomainToolkit.RemoteFunc`2.Invoke(T arg, Func`2 toInvoke)
   at AppDomainToolkit.RemoteFunc.Invoke[T,TResult](AppDomain domain, T arg1, Func`2 toInvoke) in z:\Developer\GitHu
\AppDomainToolkit\AppDomainToolkit\RemoteFunc.cs:line 76
   at DTLogic.Slave.DynamicDomain.ExecuteInvoke(InvokeRequest request) in c:\Users\Eddie\Documents\work\git\dtrunner
DT.Logic\Slave\DynamicDomain.cs:line 84

**Comment by eddiesholl** [comment]
There's definitely something wierd going on, I'm now getting other SerializationException errors in and around the class I am using to wrap my context. For example, trying to add an event handler onto context.Domain.AssemblyResolve.

I think I must be 'leaking' my non default app domain, although I've added a few log statements to check this, and AppDomain.CurrentDomain.IsDefaultAppDomain() is always true as far as I can see.

I think I need to start from scratch and build up the lifecycle of my appdomain context, making sure its clean.

**Comment by jduv** [comment]
Will give it a look later today. 

Also check for any anonymous implementations via lamdas etc. Those are never serializable.

**Comment by jduv** [comment]
So, yeah. The information I have points to some lambda that's the CLR is attempting to serialize. Can you perhaps provide an example that reproduces the problem?

**Comment by aschuhardt** [comment]
@eddiesholl were you ever able to resolve this issue?
I ran into this issue with the class described [here](https://gist.github.com/aschuhardt/e04f4003d0d7b8816ec366f66b48b8c0).

Create a new instance of the object with the static `Create` function, passing in a path to a .DLL file, exported type, and function to be executed.  Upon calling `.Execute()`, I received the same exception message that had been reported in the original issue.

**Comment by aschuhardt** [comment]
I ran into this issue today and was able to determine the cause.

This happens when the lambda passed into `.Invoke` captures something that either cannot be serialized (as opposed to primitives or `ISerializeable`).  Passing objects to the child application domain requires them to be serialized first.

I had this issue because I was passing a generic `object` instance into the lambda in the hopes of later retrieving its value and casting it to a type provided by a generic parameter.  Because `object` in itself is not serializable, .NET choked.

The solution was to pass a `MemoryStream` into the lambda, and to write the result of the lambda's logic into that (serialized with `BinaryFormatter`).  I could then deserialize the contents of the stream after the application domain was disposed and execution of the lambda had ceased.

**Comment by jduv** [comment]
Makes sense! Thanks for the update.
