### ISSUE TITLE
getting "could not load file or assembly"

### ISSUE THREAD

**Issue by moscoquera** [jduv/AppDomainToolkit#21]
hi im trying to create a object instance in a "remote domain". but when i'm finding the object class i'm getting this error:

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.FileNotFoundException: Could not load file or assembly 'kalman, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'kalman, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.Load(String assemblyString)
   at System.UnitySerializationHolder.GetRealObject(StreamingContext context)

   at AppDomainToolkit.RemoteFunc`2.Invoke(T arg, Func`2 toInvoke)
   at AppDomainToolkit.RemoteFunc.Invoke[T,TResult](AppDomain domain, T arg1, Func`2 toInvoke) in z:\Developer\GitHub\AppDomainToolkit\AppDomainToolkit\RemoteFunc.cs:line 76
   at tiempoRealComun.Objects.Method..ctor(String rutadll, Configuration conf) in c:\CodigoTransmodeler\simTiempoCercanoReal\tiempoRealComun\Objects\Method.cs:line 27
   at simTiempoCercanoReal.UI.uiConfiguration.cbxMetodos_SelectedIndexChanged(Object sender, EventArgs e) in c:\CodigoTransmodeler\simTiempoCercanoReal\simTiempoCercanoReal\UI\uiConfiguration.cs:line 174
   at simTiempoCercanoReal.UI.uiConfiguration.rellenarDesdeArchivo() in c:\CodigoTransmodeler\simTiempoCercanoReal\simTiempoCercanoReal\UI\uiConfiguration.cs:line 72
   at simTiempoCercanoReal.UI.uiConfiguration.btnLoadConfiguration_Click(Object sender, EventArgs e) in c:\CodigoTransmodeler\simTiempoCercanoReal\simTiempoCercanoReal\UI\uiConfiguration.cs:line 56
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

=== Pre-bind state information ===
LOG: DisplayName = kalman, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 (Fully-specified)
LOG: Appbase = file:///C:/Program Files (x86)/TransModeler/
LOG: Initial PrivatePath = NULL
Calling assembly : (Unknown).
===
LOG: This bind starts in default load context.
LOG: No application configuration file found.
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Policy not being applied to reference at this time (private, custom, partial, or location-based assembly bind).
LOG: The same bind was seen before, and was failed with hr = 0x80070002.

```

but when i load the dll using the "normal way", im not getting any error.

this is my source code:

```
                FileInfo fio = new FileInfo(dllpath);
                
                context.RemoteResolver.AddProbePath(fio.Directory.FullName);
                dll = context.LoadAssembly(LoadMethod.LoadFrom, dllpath);
                var methodType= RemoteFunc.Invoke(
                                        context.Domain,
                                        dll.FullName,
                                        (string fullname) =>
                                        {
                                            Assembly asm = AppDomain.CurrentDomain.GetAssemblies().Single(s => s.FullName.Equals(fullname));
                                            return asm.GetType("algoritmo", true, true);
                                        });
```

**Comment by moscoquera** [comment]
solved.

just added:
```
context.AssemblyImporter.AddProbePath(fio.Directory.FullName);
```
where fio.Directory.FullName is the path of the dll i'm loading in the remote context.
